#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
formatted_height=$(jq '.height' data.json | awk '{ printf "%.1f", $1 / 10 }')
formatted_weight=$(jq '.weight' data.json | awk '{ printf "%d", $1 / 10 }')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
