#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
height=$(jq '.height' data.json | awk '{ printf "%.1f", $1 / 10 }')
weight=$(jq '.weight' data.json | awk '{ printf "%d", $1 / 10 }')

echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
